# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zc706_board.xdc

# Block Designs: bd/Z_system/Z_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system || ORIG_REF_NAME==Z_system}]

# IP: bd/Z_system/ip/Z_system_util_ds_buf_0_0/Z_system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_util_ds_buf_0_0 || ORIG_REF_NAME==Z_system_util_ds_buf_0_0}]

# IP: bd/Z_system/ip/Z_system_xlconstant_0_0/Z_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xlconstant_0_0 || ORIG_REF_NAME==Z_system_xlconstant_0_0}]

# IP: bd/Z_system/ip/Z_system_xlconstant_0_1/Z_system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xlconstant_0_1 || ORIG_REF_NAME==Z_system_xlconstant_0_1}]

# IP: bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_processing_system7_0_0 || ORIG_REF_NAME==Z_system_processing_system7_0_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_0_0/Z_system_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_0_0 || ORIG_REF_NAME==Z_system_axi_ethernet_0_0}]

# Block Designs: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/bd_0_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_0_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_0_dma_0}]

# IP: bd/Z_system/ip/Z_system_axi_mem_intercon_0/Z_system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_mem_intercon_0 || ORIG_REF_NAME==Z_system_axi_mem_intercon_0}]

# IP: bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Z_system_rst_processing_system7_0_100M_0}]

# IP: bd/Z_system/ip/Z_system_processing_system7_0_axi_periph_0/Z_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Z_system_processing_system7_0_axi_periph_0}]

# IP: bd/Z_system/ip/Z_system_xbar_0/Z_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xbar_0 || ORIG_REF_NAME==Z_system_xbar_0}]

# IP: bd/Z_system/ip/Z_system_xbar_1/Z_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xbar_1 || ORIG_REF_NAME==Z_system_xbar_1}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_1_0/Z_system_axi_ethernet_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_1_0 || ORIG_REF_NAME==Z_system_axi_ethernet_1_0}]

# Block Designs: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/bd_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1 || ORIG_REF_NAME==bd_1}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/bd_1_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1_eth_buf_0 || ORIG_REF_NAME==bd_1_eth_buf_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/bd_1_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1_eth_mac_0 || ORIG_REF_NAME==bd_1_eth_mac_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_1_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_1_dma_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_2_0/Z_system_axi_ethernet_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_2_0 || ORIG_REF_NAME==Z_system_axi_ethernet_2_0}]

# Block Designs: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/bd_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2 || ORIG_REF_NAME==bd_2}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/bd_2_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2_eth_buf_0 || ORIG_REF_NAME==bd_2_eth_buf_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/bd_2_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2_eth_mac_0 || ORIG_REF_NAME==bd_2_eth_mac_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_2_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_2_dma_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_3_0/Z_system_axi_ethernet_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_3_0 || ORIG_REF_NAME==Z_system_axi_ethernet_3_0}]

# Block Designs: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/bd_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3 || ORIG_REF_NAME==bd_3}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/bd_3_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3_eth_buf_0 || ORIG_REF_NAME==bd_3_eth_buf_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/bd_3_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3_eth_mac_0 || ORIG_REF_NAME==bd_3_eth_mac_0}]

# IP: bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_3_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_3_dma_0}]

# IP: bd/Z_system/ip/Z_system_xlconcat_0_0/Z_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xlconcat_0_0 || ORIG_REF_NAME==Z_system_xlconcat_0_0}]

# IP: bd/Z_system/ip/Z_system_auto_pc_0/Z_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_pc_0 || ORIG_REF_NAME==Z_system_auto_pc_0}]

# IP: bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_0 || ORIG_REF_NAME==Z_system_auto_us_0}]

# IP: bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_1 || ORIG_REF_NAME==Z_system_auto_us_1}]

# IP: bd/Z_system/ip/Z_system_auto_us_2/Z_system_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_2 || ORIG_REF_NAME==Z_system_auto_us_2}]

# IP: bd/Z_system/ip/Z_system_auto_us_3/Z_system_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_3 || ORIG_REF_NAME==Z_system_auto_us_3}]

# IP: bd/Z_system/ip/Z_system_auto_us_4/Z_system_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_4 || ORIG_REF_NAME==Z_system_auto_us_4}]

# IP: bd/Z_system/ip/Z_system_auto_us_5/Z_system_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_5 || ORIG_REF_NAME==Z_system_auto_us_5}]

# IP: bd/Z_system/ip/Z_system_auto_us_6/Z_system_auto_us_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_6 || ORIG_REF_NAME==Z_system_auto_us_6}]

# IP: bd/Z_system/ip/Z_system_auto_us_7/Z_system_auto_us_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_7 || ORIG_REF_NAME==Z_system_auto_us_7}]

# IP: bd/Z_system/ip/Z_system_auto_us_8/Z_system_auto_us_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_8 || ORIG_REF_NAME==Z_system_auto_us_8}]

# IP: bd/Z_system/ip/Z_system_auto_us_9/Z_system_auto_us_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_9 || ORIG_REF_NAME==Z_system_auto_us_9}]

# IP: bd/Z_system/ip/Z_system_auto_us_10/Z_system_auto_us_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_10 || ORIG_REF_NAME==Z_system_auto_us_10}]

# IP: bd/Z_system/ip/Z_system_auto_us_11/Z_system_auto_us_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_11 || ORIG_REF_NAME==Z_system_auto_us_11}]

# IP: bd/Z_system/ip/Z_system_auto_pc_1/Z_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_pc_1 || ORIG_REF_NAME==Z_system_auto_pc_1}]

# XDC: bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_processing_system7_0_0 || ORIG_REF_NAME==Z_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/bd_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_0/synth/Z_system_axi_ethernet_0_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_0_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_0_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Z_system_rst_processing_system7_0_100M_0}]

# XDC: bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Z_system_rst_processing_system7_0_100M_0}]

# XDC: bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_xbar_0/Z_system_xbar_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_xbar_1/Z_system_xbar_1_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/bd_1_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1_eth_buf_0 || ORIG_REF_NAME==bd_1_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/synth/bd_1_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1_eth_buf_0 || ORIG_REF_NAME==bd_1_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/synth/bd_1_eth_buf_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1_eth_mac_0 || ORIG_REF_NAME==bd_1_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1_eth_mac_0 || ORIG_REF_NAME==bd_1_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1_eth_mac_0 || ORIG_REF_NAME==bd_1_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/bd_1_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_0/synth/Z_system_axi_ethernet_1_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_1_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_1_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_1_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_1_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/bd_2_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2_eth_buf_0 || ORIG_REF_NAME==bd_2_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/synth/bd_2_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2_eth_buf_0 || ORIG_REF_NAME==bd_2_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/synth/bd_2_eth_buf_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2_eth_mac_0 || ORIG_REF_NAME==bd_2_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2_eth_mac_0 || ORIG_REF_NAME==bd_2_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2_eth_mac_0 || ORIG_REF_NAME==bd_2_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/bd_2_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_0/synth/Z_system_axi_ethernet_2_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_2_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_2_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_2_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_2_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/bd_3_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3_eth_buf_0 || ORIG_REF_NAME==bd_3_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/synth/bd_3_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3_eth_buf_0 || ORIG_REF_NAME==bd_3_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/synth/bd_3_eth_buf_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3_eth_mac_0 || ORIG_REF_NAME==bd_3_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3_eth_mac_0 || ORIG_REF_NAME==bd_3_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3_eth_mac_0 || ORIG_REF_NAME==bd_3_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/bd_3_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_0/synth/Z_system_axi_ethernet_3_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_3_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_3_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_axi_ethernet_3_dma_0 || ORIG_REF_NAME==Z_system_axi_ethernet_3_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/Z_system/ip/Z_system_auto_pc_0/Z_system_auto_pc_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_0 || ORIG_REF_NAME==Z_system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_1 || ORIG_REF_NAME==Z_system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_2/Z_system_auto_us_2_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_2/Z_system_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_2 || ORIG_REF_NAME==Z_system_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_3/Z_system_auto_us_3_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_3/Z_system_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_3 || ORIG_REF_NAME==Z_system_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_4/Z_system_auto_us_4_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_4/Z_system_auto_us_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_4 || ORIG_REF_NAME==Z_system_auto_us_4}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_5/Z_system_auto_us_5_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_5/Z_system_auto_us_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_5 || ORIG_REF_NAME==Z_system_auto_us_5}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_6/Z_system_auto_us_6_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_6/Z_system_auto_us_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_6 || ORIG_REF_NAME==Z_system_auto_us_6}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_7/Z_system_auto_us_7_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_7/Z_system_auto_us_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_7 || ORIG_REF_NAME==Z_system_auto_us_7}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_8/Z_system_auto_us_8_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_8/Z_system_auto_us_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_8 || ORIG_REF_NAME==Z_system_auto_us_8}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_9/Z_system_auto_us_9_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_9/Z_system_auto_us_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_9 || ORIG_REF_NAME==Z_system_auto_us_9}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_10/Z_system_auto_us_10_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_10/Z_system_auto_us_10_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_10 || ORIG_REF_NAME==Z_system_auto_us_10}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_us_11/Z_system_auto_us_11_ooc.xdc

# XDC: bd/Z_system/ip/Z_system_auto_us_11/Z_system_auto_us_11_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Z_system_auto_us_11 || ORIG_REF_NAME==Z_system_auto_us_11}] {/inst }]/inst ]]

# XDC: bd/Z_system/ip/Z_system_auto_pc_1/Z_system_auto_pc_1_ooc.xdc

# XDC: bd/Z_system/Z_system_ooc.xdc
