# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z045ffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/base_zc706/base_zc706.cache/wt [current_project]
set_property parent.project_path /root/base_zc706/base_zc706.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.1 [current_project]
set_property ip_repo_paths /root/base_zc706/ip [current_project]
add_files /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/Z_system.bd
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/bd_0/bd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_0/synth/Z_system_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_0_dma_0/Z_system_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_rst_processing_system7_0_100M_0/Z_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_xbar_0/Z_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_xbar_1/Z_system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/bd_1_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/synth/bd_1_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_0/synth/bd_1_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/ip/ip_1/synth/bd_1_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/bd_1/bd_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_0/synth/Z_system_axi_ethernet_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_1_dma_0/Z_system_axi_ethernet_1_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/bd_2_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/synth/bd_2_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_0/synth/bd_2_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/ip/ip_1/synth/bd_2_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/bd_2/bd_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_0/synth/Z_system_axi_ethernet_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_2_dma_0/Z_system_axi_ethernet_2_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/bd_3_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/synth/bd_3_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_0/synth/bd_3_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/ip/ip_1/synth/bd_3_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/bd_3/bd_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_0/synth/Z_system_axi_ethernet_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_axi_ethernet_3_dma_0/Z_system_axi_ethernet_3_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_pc_0/Z_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_2/Z_system_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_2/Z_system_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_3/Z_system_auto_us_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_3/Z_system_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_4/Z_system_auto_us_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_4/Z_system_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_5/Z_system_auto_us_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_5/Z_system_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_6/Z_system_auto_us_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_6/Z_system_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_7/Z_system_auto_us_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_7/Z_system_auto_us_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_8/Z_system_auto_us_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_8/Z_system_auto_us_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_9/Z_system_auto_us_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_9/Z_system_auto_us_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_10/Z_system_auto_us_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_10/Z_system_auto_us_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_11/Z_system_auto_us_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_11/Z_system_auto_us_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/ip/Z_system_auto_pc_1/Z_system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/Z_system_ooc.xdc]
set_property is_locked true [get_files /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/Z_system.bd]

read_verilog -library xil_defaultlib /root/base_zc706/base_zc706.srcs/sources_1/bd/Z_system/hdl/Z_system_wrapper.v
read_xdc /root/base_zc706/base_zc706.srcs/constrs_1/new/zc706_board.xdc
set_property used_in_implementation false [get_files /root/base_zc706/base_zc706.srcs/constrs_1/new/zc706_board.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file Z_system_wrapper.hwdef }
synth_design -top Z_system_wrapper -part xc7z045ffg900-2
write_checkpoint -noxdef Z_system_wrapper.dcp
catch { report_utilization -file Z_system_wrapper_utilization_synth.rpt -pb Z_system_wrapper_utilization_synth.pb }
